### Numpy
- 데이터는 행렬로 표현
- 행열 데이터를 빠르게 계산
- 행열 데이터 생성, 수정, 계산등을 빠르게 처리해주는 패키지
- 특징 
    - C, C++, 포트란으로 작성
    - 선형대수학으로 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [4]:
import numpy as np

In [13]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 사용 가능

array = np.array([1,2,3])

In [6]:
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [9]:
# 행렬 데이터 생성

array2 = np.array(
    [[1,2,3],
    [4,5,6]]
)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
'array2는 {}차원 행열이고 {}행 {}열 입니다.'.format(array2.ndim, array2.shape[0], array2.shape[1])

'array2는 2차원 행열이고 2행 3열 입니다.'

In [15]:
# 행렬의 모양(shap) 변경하기
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
# 행렬 데이터의 선택 : offset index : masking
array2[0], array2[1], array2[0][1], array2[0,1]

(array([1, 2, 3]), array([4, 5, 6]), 2, 2)

In [22]:
# 브로드 케스팅

print(array2[0,1])
array2[0,1] = 100
print(array2[0,1])
print(array2)

2
100
[[  1 100   3]
 [  4   5   6]]


In [25]:
# 조건으로 선택
# 메트릭스 > 스칼라 <-> array2 > 7
idx = array2 > 7
idx

array([[False,  True, False],
       [False, False, False]])

In [26]:
# idx에 True인 스칼라만 남기고 False인 데이터는 삭제
array2[idx] 

array([100])

In [37]:
# arrar2 의 스칼라 값이 7이상인 데이터는 111로 치환하라
array2[idx] = 111

In [38]:
array2

array([[  1, 111,   3],
       [  4,   5,   6]])

In [39]:
array2.reshape(6)

array([  1, 111,   3,   4,   5,   6])

In [44]:
# 행렬 데이터의 생성 2
data = np.zeros((2,3))
data, data.dtype

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 dtype('float64'))

In [45]:
data.astype("int"), data.astype("int").dtype

(array([[0, 0, 0],
        [0, 0, 0]]),
 dtype('int32'))

In [47]:
data2 = np.ones((2,5,6)).astype("int")
data2

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [51]:
# arange
np.arange(5),np.arange(5,10),np.arange(5,10,2)

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([5, 7, 9]))